# Generated by Django 5.1.6 on 2025-12-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='club',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='text',
            field=models.TextField(),
        ),
    ]
